

services:
  app:
    build: .
    volumes:
      - .:/django 
    ports:
      - "8000:8000"  
    image: application:django  
    container_name: app_container  
    command: gunicorn taskly.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=taskly.settings  
