global:
  scrape_interval: 15s  # How often Prometheus will scrape targets

scrape_configs:
  - job_name: 'monitoring'
    metrics_path: /metrics  
    static_configs:
      - targets: 
        - 65.2.4.202:8000  # Specify the port Prometheus should scrape
        - 65.2.4.202:8001  
